### ISSUE TITLE
URL Routing not working

### ISSUE THREAD

**Issue by angelo-v** [hadfieldn/storybook-filepath-chapters#1]
**Actual behaviour:**
Given I opened a story
When I refresh the page
*Then I am at the root of the storybook*

**Expected behaviour:**
Given I opened a story
When I refresh the page
*Then the story is still open*

**Comment by angelo-v** [comment]
I just noticed, it does not work in [sm-react/storybook-chapters](https://github.com/sm-react/storybook-chapters) as well, so I opened an issue there. Please close this one, if you do not have an influence on the behaviour within this project

**Comment by hadfieldn** [comment]
Thanks for noting this @angelo-v. It is indeed an issue in sm-react/storybook-chapters.

**Comment by usulpro** [comment]
https://github.com/sm-react/storybook-chapters/releases/tag/0.4.0

need to register the addon to enable

**Comment by kaiserkoenig** [comment]
any updates?
