### ISSUE TITLE
Contact the maintainers of storybook

### ISSUE THREAD

**Issue by ndelangen** [hadfieldn/storybook-filepath-chapters#3]
Hey! awesome addon, Can you join us in the storybook slack?
https://storybooks-slackin.herokuapp.com/

That way we can keep you updated on the upcoming 3.0.0 release! 

❤️ storybook team

**Comment by hadfieldn** [comment]
Hi @ndelangen, thanks for the invitation. I'm already there as hadfieldn. It's great to see all the effort being put into Storybook lately. Thanks for all you're doing!
